services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - main-network

networks:
  main-network:
    driver: bridge