services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - main-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  main-network:
    external: true