services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app