name: Deploy Portfolio on Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t \
          portfolio:latest .

      - name: Deploy Docker container
        run: |
          docker stop portfolio-container || true
          docker rm portfolio-container || true
          docker run -d \
          -p 3000:3000 \
          --name portfolio-container \
          portfolio:latest